# example netlify.toml
[build]
  command = "npm run build"
  functions = "functions"
  publish = "_site"
  base = "site"
  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.

  [[redirects]]
    from = "/:slug/"
    to = "/.netlify/functions/madlib"
    status = 200
    force = true
    _generated_by_eleventy_serverless = "madlib"
    
  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
